jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:  # 👇 Adicione essas permissões!
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # ... (resto do seu workflow)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token automático do GitHub
          publish_dir: ./dist